const english = {
  backToPlayroom: 'Back to Playroom',
  backToShop: 'Back to Shop',
  howToPlay: 'How to Play',
  toggleSound: 'Toggle sound',
  resumeGame: 'Resume game',
  pauseGame: 'Pause game',
  title: 'Ashlife Swing & Win',
  description: 'Position, drop, grab, build momentum, then release at the perfect moment.',
  modePanelAria: 'Game mode and difficulty',
  modes: {
    practice: { label: 'Practice', note: 'Unlimited tries' },
    classic: { label: 'Classic', note: 'Rewards enabled' },
  },
  difficulties: { easy: 'Easy', normal: 'Normal', hard: 'Hard' },
  completedToday: 'Completed today',
  unlimited: 'Unlimited',
  controlsTitle: 'Controls',
  controls: {
    move: 'Move',
    moveKeys: 'Arrow keys or A / D',
    dropGrab: 'Drop / Grab',
    dropGrabKey: 'Space',
    release: 'Release',
    releaseKey: 'R',
    pause: 'Pause',
    pauseKey: 'Esc or P',
    rightHanded: 'Right-handed controls',
    leftHanded: 'Left-handed controls',
    explore: 'Explore Related Products',
  },
  hud: {
    aria: 'Ashlife Swing & Win status',
    joyCoins: 'Joy Coins',
    restart: 'Restart',
    restartLocked: 'Classic sessions cannot be restarted after the first try.',
    liveAria: 'Live game status',
    live: 'Live status',
    tries: 'Tries',
    timeLeft: 'Time left',
    swing: 'Swing',
    swingPower: (power) => `Swing power ${power}%`,
  },
  mobile: {
    aria: 'Touch controls',
    moveLeft: 'Move left',
    moveRight: 'Move right',
    dropGrab: 'Drop / Grab',
    release: 'Release',
  },
  session: {
    aria: 'Won prizes this session',
    thisSession: 'This session',
    wonPrizes: 'Won Prizes',
    classic: 'Classic',
    practice: 'Practice',
    dollsWon: 'dolls won',
    sessionCoins: 'session coins',
    empty: 'Prizes collected through the chute will appear here.',
  },
  summary: {
    aria: 'Classic session summary',
    complete: 'Classic Complete!',
    title: 'Your Prize Haul',
    lead: (count) =>
      count
        ? `You clawed ${count} ${count === 1 ? 'doll' : 'dolls'} today!`
        : 'No dolls this time, but the machine will be ready again tomorrow.',
    dolls: 'dolls',
    joyCoins: 'Joy Coins',
    triesUsed: 'tries used',
    collectedAria: 'Collected prizes',
    coins: 'coins',
    dailyNote: 'Classic refreshes tomorrow. Practice mode is always available.',
    practice: 'Play Practice',
    back: 'Back to Playroom',
  },
  tutorial: {
    aria: 'How to play Ashlife Swing and Win',
    label: 'How to Play',
    title: 'Swing, Grab & Drop',
    close: 'Close how to play',
    steps: [
      'Move left or right to position the trolley above a prize.',
      'Press Drop, then press Drop / Grab again to close the claw.',
      'Move with the swing to build momentum.',
      'Counter-swing to slow down and aim more carefully.',
      'Release at the right moment so the prize lands in the hole.',
    ],
    start: 'Start Playing',
  },
  loading: {
    canvasAria: 'Ashlife Swing and Win game canvas',
    loading: 'Loading Ashlife Swing & Win...',
    preparing: 'Preparing prizes, cable and cozy cafe lights.',
    reset: 'The machine needs a quick reset.',
    error: 'Phaser could not initialize. Please refresh the game route.',
  },
  status: {
    READY: 'Move the claw',
    AIMING: 'Press Drop',
    DROPPING: 'Close the claw',
    GRABBING: 'Checking grip',
    CLOSING: 'Closing claw',
    LIFTING: 'Lifting',
    SWINGING: 'Build momentum!',
    RELEASED: 'Prize released',
    RESOLVING: 'So close!',
    SUCCESS: 'Prize won!',
    FAILED: 'Try again',
    PAUSED: 'Paused',
    slipping: 'Prize slipping!',
    collected: 'Prize collected!',
    classicComplete: 'Classic complete!',
    prizeCollected: (name) => `${name} collected!`,
  },
  grip: {
    missed: 'Missed',
    weak: 'Weak Grip',
    unstable: 'Unstable Grip',
    secure: 'Secure Grip',
    hooked: 'Hooked!',
  },
  scene: {
    instruction: 'Swing, release, drop it in!',
    wonPrizes: 'WON PRIZES',
    dropHere: 'DROP\nHERE!',
  },
  prizes: {
    'bunny-plush': 'Bunny Plush',
    'bear-plush': 'Bear Plush',
    'chick-plush': 'Chick Plush',
    'bunny-pencil-case': 'Bunny Pencil Case',
    'washi-tape-roll': 'Pink Washi Tape Roll',
    'heart-keychain': 'Heart Keychain',
    'calico-cat-plush': 'Calico Cat Plush',
    'strawberry-milk-carton': 'Strawberry Milk Carton',
    'star-cushion': 'Smiling Star Cushion',
    'pink-toy-car': 'Heartlight Toy Car',
    'cloud-plush': 'Rainbow Cloud Plush',
    'strawberry-donut': 'Strawberry Donut Plush',
    'cherry-handbag': 'Cherry Handbag Plush',
  },
};

const chinese = {
  backToPlayroom: '返回游戏天地',
  backToShop: '返回商店',
  howToPlay: '玩法说明',
  toggleSound: '切换声音',
  resumeGame: '继续游戏',
  pauseGame: '暂停游戏',
  title: 'Ashlife 摇摆抓奖',
  description: '移动、下爪、抓取并制造摇摆，在最合适的时机放开奖品。',
  modePanelAria: '游戏模式和难度',
  modes: {
    practice: { label: '练习', note: '无限次数' },
    classic: { label: '经典', note: '可获得奖励' },
  },
  difficulties: { easy: '简单', normal: '普通', hard: '困难' },
  completedToday: '今天已完成',
  unlimited: '无限',
  controlsTitle: '操作方式',
  controls: {
    move: '移动',
    moveKeys: '方向键或 A / D',
    dropGrab: '下爪 / 抓取',
    dropGrabKey: '空格键',
    release: '放开',
    releaseKey: 'R',
    pause: '暂停',
    pauseKey: 'Esc 或 P',
    rightHanded: '右手操作',
    leftHanded: '左手操作',
    explore: '浏览相关商品',
  },
  hud: {
    aria: 'Ashlife 摇摆抓奖状态',
    joyCoins: '欢乐币',
    restart: '重新开始',
    restartLocked: '经典模式开始第一次尝试后无法重新开始。',
    liveAria: '即时游戏状态',
    live: '即时状态',
    tries: '剩余次数',
    timeLeft: '剩余时间',
    swing: '摇摆力度',
    swingPower: (power) => `摇摆力度 ${power}%`,
  },
  mobile: {
    aria: '触控操作',
    moveLeft: '向左移动',
    moveRight: '向右移动',
    dropGrab: '下爪 / 抓取',
    release: '放开',
  },
  session: {
    aria: '本局赢得的奖品',
    thisSession: '本局记录',
    wonPrizes: '已赢奖品',
    classic: '经典',
    practice: '练习',
    dollsWon: '个奖品',
    sessionCoins: '本局欢乐币',
    empty: '从洞口收集到的奖品会显示在这里。',
  },
  summary: {
    aria: '经典模式本局总结',
    complete: '经典模式完成！',
    title: '您的奖品',
    lead: (count) => (count ? `今天成功抓到 ${count} 个奖品！` : '这次还没抓到奖品，明天可以再挑战经典模式。'),
    dolls: '个奖品',
    joyCoins: '欢乐币',
    triesUsed: '已用次数',
    collectedAria: '已收集奖品',
    coins: '欢乐币',
    dailyNote: '经典模式明天重置，练习模式随时可以游玩。',
    practice: '玩练习模式',
    back: '返回游戏天地',
  },
  tutorial: {
    aria: 'Ashlife 摇摆抓奖玩法说明',
    label: '玩法说明',
    title: '摇摆、抓取、投奖',
    close: '关闭玩法说明',
    steps: [
      '向左或向右移动，把爪子对准奖品上方。',
      '按下爪，再按一次“下爪 / 抓取”来合上爪子。',
      '配合摇摆移动来增加动力。',
      '反方向移动可以减慢摇摆，帮助您更准确地瞄准。',
      '在合适的时机放开，让奖品落入洞口。',
    ],
    start: '开始游戏',
  },
  loading: {
    canvasAria: 'Ashlife 摇摆抓奖游戏画面',
    loading: '正在载入 Ashlife 摇摆抓奖…',
    preparing: '正在准备奖品、吊线和温馨咖啡厅灯光。',
    reset: '抓娃娃机需要快速重置。',
    error: '游戏无法启动，请刷新此页面。',
  },
  status: {
    READY: '移动爪子',
    AIMING: '按下爪',
    DROPPING: '再次按下以抓取',
    GRABBING: '正在检查抓力',
    CLOSING: '正在合上爪子',
    LIFTING: '正在升起',
    SWINGING: '增加摇摆动力！',
    RELEASED: '奖品已放开',
    RESOLVING: '差一点！',
    SUCCESS: '抓到奖品！',
    FAILED: '再试一次',
    PAUSED: '已暂停',
    slipping: '奖品正在滑落！',
    collected: '奖品已收集！',
    classicComplete: '经典模式完成！',
    prizeCollected: (name) => `已收集${name}！`,
  },
  grip: {
    missed: '没有抓到',
    weak: '抓力偏弱',
    unstable: '抓取不稳',
    secure: '抓得很稳',
    hooked: '成功勾住！',
  },
  scene: {
    instruction: '摇摆、放开，把奖品投进洞口！',
    wonPrizes: '已赢奖品',
    dropHere: '投进\n这里！',
  },
  prizes: {
    'bunny-plush': '兔子玩偶',
    'bear-plush': '小熊玩偶',
    'chick-plush': '小鸡玩偶',
    'bunny-pencil-case': '兔子笔袋',
    'washi-tape-roll': '粉色和纸胶带',
    'heart-keychain': '爱心钥匙圈',
    'calico-cat-plush': '三花猫玩偶',
    'strawberry-milk-carton': '草莓牛奶盒玩偶',
    'star-cushion': '笑脸星星抱枕',
    'pink-toy-car': '爱心灯光玩具车',
    'cloud-plush': '彩虹云朵玩偶',
    'strawberry-donut': '草莓甜甜圈玩偶',
    'cherry-handbag': '樱桃手提包玩偶',
  },
};

export function getClawMachineCopy(language) {
  return language === 'zh' ? chinese : english;
}
