const english = {
  backToPlayroom: 'Back to Playroom',
  title: 'Badge Studio',
  subtitle: 'Design your own 58 mm badges, then build a print-ready A4 sheet.',
  progressAria: 'Badge Studio progress',
  steps: ['Upload', 'Customize', 'Arrange', 'Details', 'Finish'],
  draft: {
    new: 'New project',
    restored: 'Draft restored',
    unavailable: 'Draft saving unavailable',
    saving: 'Saving…',
    saved: 'Draft saved',
  },
  notices: {
    maxPhotos: (count) => `You can use up to ${count} photos in one project.`,
    maxBadges: (count) => `One project can contain up to ${count} badges.`,
    limitReached: 'This project has reached its design or badge limit.',
    prepareFailed: 'The print files could not be prepared.',
    addPhoto: 'Add at least one photo to start your badge collection.',
    imageOpenFailed: (name) => `${name} could not be opened as an image.`,
  },
  validation: {
    unsupportedType: 'Use a JPG, PNG, or WebP image.',
    tooLarge: 'This image is larger than 15 MB.',
    name: 'Enter your name.',
    whatsapp: 'Enter a valid WhatsApp number.',
    designChecked: 'Confirm that you checked the design.',
    lowResolutionAccepted: 'Accept the low-resolution warning to continue.',
  },
  upload: {
    title: 'Upload your photos',
    description: 'Each photo becomes one badge design automatically. You can adjust and duplicate it next.',
    choosePhotos: 'Choose photos',
    limits: 'JPG, PNG or WebP · up to 20 photos · 15 MB each',
    privacyTitle: 'Your photos stay on this device while you design.',
    privacyDescription: 'Only completed print files, the preview, and order details are sent when you choose Submit.',
  },
  canvas: {
    instruction: 'Move and zoom until the important part stays inside the safe circle.',
    quality: {
      good: 'Good quality',
      acceptable: 'Acceptable quality',
      low: 'Low resolution',
    },
    editorAria: 'Badge photo editor. Drag the photo to reposition it.',
    legendAria: 'Badge guide legend',
    artworkEdge: 'Artwork edge 70 mm',
    safeArea: 'Safe area 54 mm',
    zoom: 'Zoom',
    rotation: 'Rotation',
    rotateLeft: 'Rotate left',
    rotateRight: 'Rotate right',
    reset: 'Reset',
    replacePhoto: 'Replace photo',
  },
  designs: {
    title: 'Your designs',
    badgeLimit: (total, max) => `${total} of ${max} badges`,
    addPhotosAria: 'Add photos',
    design: 'Design',
    quality: {
      good: 'good',
      acceptable: 'acceptable',
      low: 'low',
    },
    quantityAria: (number) => `Quantity for design ${number}`,
    decrease: 'Decrease quantity',
    increase: 'Increase quantity',
    edit: 'Edit',
    duplicate: 'Duplicate',
    delete: 'Delete',
    addMore: 'Add more photos',
    limits: 'JPG, PNG or WebP · up to 15 MB each',
  },
  arrange: {
    title: 'Arrange your print sheets',
    description: 'Quantities are filled automatically. Use the arrows on a badge to swap its print order.',
    badges: 'badges',
    sheet: 'A4 sheet',
    sheets: 'A4 sheets',
    artwork: 'artwork',
    sheetSelectionAria: 'Print sheet selection',
    sheetLabel: 'Sheet',
    calibration: 'The default uses 8 non-overlapping 70 mm circles. Print one test at 100% scale before production.',
    empty: 'Empty',
    emptySlots: 'empty slots',
    printSheetAria: (number) => `A4 print sheet ${number}`,
    moveLeft: 'Move badge left',
    moveRight: 'Move badge right',
  },
  details: {
    title: 'Who is this badge collection for?',
    description: 'These details help Ashlife match your print files with your WhatsApp order.',
    name: 'Name *',
    whatsapp: 'WhatsApp number *',
    email: 'Email (optional)',
    orderType: 'Order type',
    direct: 'Direct / WhatsApp',
    shopee: 'Shopee',
    tiktok: 'TikTok Shop',
    pickup: 'Store pickup',
    marketplaceNumber: 'Marketplace order number',
    notes: 'Notes (optional)',
    website: 'Website',
    checked: 'I checked every badge and kept important details inside the safe circle.',
    lowResolution: 'I understand that low-resolution photos may look blurry when printed.',
  },
  finish: {
    submitted: 'Your badge design was submitted!',
    ready: 'Your print files are ready',
    preparing: 'Preparing 300 DPI print files…',
    printPdf: 'Print PDF',
    a4Png: 'A4 PNG',
    previewJpg: 'Preview JPG',
    orderInfo: 'Order info',
    cancelUpload: 'Cancel upload',
    uploadFailedTitle: 'Automatic upload did not finish.',
    retryUpload: 'Retry Drive upload',
    submit: 'Submit to Ashlife',
    endpointMissing: 'Automatic Drive submission is not configured yet. Download the PDF and send it through WhatsApp.',
    contactWhatsapp: 'Contact Ashlife on WhatsApp',
    uploadCancelled: 'Upload cancelled.',
    uploadFailed: 'The automatic upload could not be completed.',
    starting: 'Starting your order…',
    uploading: (fileName) => `Uploading ${fileName}`,
    finalizing: 'Finalizing your order…',
    complete: 'Order submitted successfully.',
  },
  action: {
    back: 'Back',
    prepare: 'Prepare print files',
    badge: 'badge',
    badges: 'badges',
    sheet: 'A4 sheet',
    sheets: 'A4 sheets',
  },
  loading: 'Opening your craft table…',
  whatsappMessage: ({ orderId, quantity, sheets, name }) =>
    `Hi Ashlife, I have completed my badge design.\n\nOrder ID: ${orderId || 'Not submitted yet'}\nBadge size: 58 mm\nQuantity: ${quantity}\nA4 sheets: ${sheets}\nCustomer name: ${name || '-'}\n\nPlease help me check the design and confirm the order. Thank you.`,
};

const chinese = {
  backToPlayroom: '返回游戏天地',
  title: '徽章设计室',
  subtitle: '自己设计 58 mm 徽章，并自动排成可打印的 A4 文件。',
  progressAria: '徽章设计进度',
  steps: ['上传', '调整', '排版', '资料', '完成'],
  draft: {
    new: '新设计',
    restored: '已恢复草稿',
    unavailable: '无法保存草稿',
    saving: '正在保存…',
    saved: '草稿已保存',
  },
  notices: {
    maxPhotos: (count) => `每个设计最多可使用 ${count} 张照片。`,
    maxBadges: (count) => `每个设计最多可包含 ${count} 个徽章。`,
    limitReached: '此设计已达到照片或徽章数量上限。',
    prepareFailed: '无法准备打印文件。',
    addPhoto: '请至少添加一张照片来开始设计徽章。',
    imageOpenFailed: (name) => `无法打开图片：${name}`,
  },
  validation: {
    unsupportedType: '请使用 JPG、PNG 或 WebP 图片。',
    tooLarge: '这张图片大于 15 MB。',
    name: '请输入姓名。',
    whatsapp: '请输入有效的 WhatsApp 号码。',
    designChecked: '请确认您已经检查设计。',
    lowResolutionAccepted: '请接受低清晰度提示后继续。',
  },
  upload: {
    title: '上传您的照片',
    description: '每张照片会自动变成一个徽章设计，下一步可以调整、复制和设置数量。',
    choosePhotos: '选择照片',
    limits: 'JPG、PNG 或 WebP · 最多 20 张 · 每张 15 MB',
    privacyTitle: '设计期间，照片会保留在您的设备中。',
    privacyDescription: '只有完成的打印文件、预览图和订单资料会在您提交时发送。',
  },
  canvas: {
    instruction: '移动和缩放照片，把重要内容保持在安全圆圈内。',
    quality: {
      good: '清晰度良好',
      acceptable: '清晰度可接受',
      low: '清晰度偏低',
    },
    editorAria: '徽章照片编辑器。拖动照片可以调整位置。',
    legendAria: '徽章辅助线说明',
    artworkEdge: '图稿边缘 70 mm',
    safeArea: '安全范围 54 mm',
    zoom: '缩放',
    rotation: '旋转',
    rotateLeft: '向左旋转',
    rotateRight: '向右旋转',
    reset: '重置',
    replacePhoto: '更换照片',
  },
  designs: {
    title: '您的设计',
    badgeLimit: (total, max) => `${total} / ${max} 个徽章`,
    addPhotosAria: '添加照片',
    design: '设计',
    quality: {
      good: '良好',
      acceptable: '可接受',
      low: '偏低',
    },
    quantityAria: (number) => `设计 ${number} 的数量`,
    decrease: '减少数量',
    increase: '增加数量',
    edit: '编辑',
    duplicate: '复制',
    delete: '删除',
    addMore: '添加更多照片',
    limits: 'JPG、PNG 或 WebP · 每张最多 15 MB',
  },
  arrange: {
    title: '安排打印版面',
    description: '系统会根据数量自动填充。使用徽章上的箭头可以交换打印顺序。',
    badges: '个徽章',
    sheet: '张 A4',
    sheets: '张 A4',
    artwork: '图稿',
    sheetSelectionAria: '选择打印页',
    sheetLabel: '第',
    calibration: '默认使用 8 个互不重叠的 70 mm 圆形。正式制作前，请先按 100% 比例测试打印一张。',
    empty: '空白',
    emptySlots: '个空位',
    printSheetAria: (number) => `A4 打印页 ${number}`,
    moveLeft: '将徽章向前移动',
    moveRight: '将徽章向后移动',
  },
  details: {
    title: '这组徽章是为谁设计的？',
    description: '这些资料可帮助 Ashlife 将打印文件与您的 WhatsApp 订单配对。',
    name: '姓名 *',
    whatsapp: 'WhatsApp 号码 *',
    email: '电邮（选填）',
    orderType: '订单类型',
    direct: '直接订购 / WhatsApp',
    shopee: 'Shopee',
    tiktok: 'TikTok Shop',
    pickup: '到店自取',
    marketplaceNumber: '平台订单编号',
    notes: '备注（选填）',
    website: '网站',
    checked: '我已检查每个徽章，并把重要内容保持在安全圆圈内。',
    lowResolution: '我明白低清晰度照片打印后可能会模糊。',
  },
  finish: {
    submitted: '您的徽章设计已成功提交！',
    ready: '打印文件已准备好',
    preparing: '正在准备 300 DPI 打印文件…',
    printPdf: '打印 PDF',
    a4Png: 'A4 PNG',
    previewJpg: '预览 JPG',
    orderInfo: '订单资料',
    cancelUpload: '取消上传',
    uploadFailedTitle: '自动上传未能完成。',
    retryUpload: '重试上传到云端硬盘',
    submit: '提交给 Ashlife',
    endpointMissing: '尚未设置自动提交到云端硬盘。请下载 PDF 后通过 WhatsApp 发送。',
    contactWhatsapp: '通过 WhatsApp 联系 Ashlife',
    uploadCancelled: '上传已取消。',
    uploadFailed: '自动上传无法完成。',
    starting: '正在建立订单…',
    uploading: (fileName) => `正在上传 ${fileName}`,
    finalizing: '正在完成订单…',
    complete: '订单已成功提交。',
  },
  action: {
    back: '返回',
    prepare: '准备打印文件',
    badge: '个徽章',
    badges: '个徽章',
    sheet: '张 A4',
    sheets: '张 A4',
  },
  loading: '正在打开徽章设计室…',
  whatsappMessage: ({ orderId, quantity, sheets, name }) =>
    `您好 Ashlife，我已经完成徽章设计。\n\n订单编号：${orderId || '尚未提交'}\n徽章尺寸：58 mm\n数量：${quantity}\nA4 页数：${sheets}\n顾客姓名：${name || '-'}\n\n请帮我检查设计并确认订单，谢谢。`,
};

export function getBadgeStudioCopy(language) {
  return language === 'zh' ? chinese : english;
}
