const en = {
  title: 'Ashlife Gift Rush', eyebrow: 'A little parcel. A lot of joy.',
  description: 'Pick their favourites, tie a little bow, and make someone smile.',
  cardDescription: 'Pack cute gifts for bunny, bear and chick customers. Keep your perfect-order combo going!',
  cardType: 'Quick orders + combos', cardReward: 'Daily Joy Coins + collectible sticker', playNow: 'Play Now',
  back: 'Back to Playroom', practice: 'Practice', daily: 'Daily Challenge',
  practiceNote: 'Unlimited rounds · play for the joy of it', dailyNote: 'One daily goal · 20 Joy Coins',
  start: 'Start Game', replay: 'Play Again', tutorial: 'How to Play', close: 'Close',
  chooseMode: 'Your little gift counter', modeHint: 'A 90-second rush of happy deliveries.', counterSign: 'GIFT COUNTER', setupLabel: '90 SECONDS OF JOY',
  score: 'Score', best: 'Personal best', combo: 'Perfect combo', time: 'Time left',
  served: 'Gifts delivered', perfect: 'Perfect orders', maxCombo: 'Best combo',
  coins: 'Joy Coins', pause: 'Pause', resume: 'Resume Game', restart: 'Restart', soundOn: 'Enable sound', soundOff: 'Mute sound',
  paused: 'A little breather', pausedNote: 'Your customers can wait. The clock is paused.',
  waiting: 'Next customer on the way!', waitingNote: 'Your shelf is ready. A new request will arrive soon.',
  request: 'Their little wish list', tray: 'Your gift tray', shelf: 'Pick the little things',
  wrapping: 'Finish with a little bow', clear: 'Clear Tray', pack: 'Pack Gift',
  selectCustomer: 'Choose a customer', emptySlot: 'Empty gift slot',
  remove: 'Remove', patience: 'seconds left', wrapNeeded: 'Requested wrapping',
  waitingBadge: 'Waiting', servingBadge: 'Packing now', giftFor: 'A gift for',
  perfectDelivery: 'Perfect parcel!', delivery: 'Delivered with love!',
  wrongItems: 'Check the items and quantities. −3 seconds',
  wrongWrap: 'Try their requested wrapping. −3 seconds',
  expired: 'They had to go. The next parcel is a fresh start.',
  roundFinished: 'Your shift is complete!', results: 'Little gifts, happy hearts.',
  resultsNote: 'Every parcel was a little moment of joy.',
  goal: 'Today’s little mission', goalDone: 'Daily goal complete!',
  dailyGoals: { 'perfect-five': 'Deliver 5 perfect parcels in one round.', 'serve-ten': 'Deliver 10 parcels in one round.', 'combo-four': 'Reach a perfect-order combo of 4.' },
  rewardPending: 'Your 20 Joy Coins are pending. You can retry when your wallet is ready.',
  rewardCredited: '20 Joy Coins claimed for this day!',
  rewardAlready: 'Today’s reward is already claimed. Keep playing for a new personal best!',
  rewardIncomplete: 'Try another Daily round to finish your mission.',
  practiceReward: 'Practice is for points and smiles. Play Daily for Joy Coins.',
  claim: 'Claim Reward', retry: 'Retry Reward', walletWait: 'Your wallet is getting ready.',
  walletChanged: 'This reward belongs to the wallet that earned it. Return to that account to retry.',
  pendingTitle: 'A reward waiting for you', stickerUnlocked: 'Happy Parcel sticker unlocked!',
  stickerHint: 'Deliver 5 perfect parcels in a round to collect your Happy Parcel sticker.',
  leaveTitle: 'Leave this little shift?', leaveNote: 'This round will end without saving its score or rewards.',
  leave: 'Leave Game', restartTitle: 'Start a fresh shift?', restartNote: 'Your current round will be abandoned.',
  confirmRestart: 'Start Fresh', cancel: 'Keep Playing',
  tutorialSteps: [
    'Choose a customer and read their product icons, quantities, and wrapping.',
    'Tap shelf items to fill their tray. Tap a tray item to remove it.',
    'Choose the matching wrapping and tap Pack Gift. A wrong Pack costs 3 seconds of patience.',
    'Keep perfect parcels coming for combos. You have 90 seconds; pause whenever you need.',
  ],
  customers: { bunny: 'Bunny', bear: 'Bear', chick: 'Chick' },
  products: { 'bear-notebook': 'Bear Notebook', 'bunny-pencil-case': 'Bunny Pencil Case', 'bear-heart': 'Heart Keychain', 'bubble-tea-keychain': 'Bubble Tea Keychain', 'paw-squishy': 'Paw Squishy', 'kawaii-washi-tape': 'Kawaii Washi Tape' },
  wraps: { 'pink-hearts': 'Pink Hearts', 'lavender-stars': 'Lavender Stars', 'mint-dots': 'Mint Dots' },
};
const zh = {
  title: 'Ashlife 礼物快递', eyebrow: '小小包裹，满满欢乐。',
  description: '挑选心爱的小物，系上蝴蝶结，为他们送去微笑。',
  cardDescription: '为兔兔、小熊和小鸡打包可爱礼物，连续完美送达，获得更高分！',
  cardType: '快速订单 + 连击', cardReward: '每日 Joy Coins + 收藏贴纸', playNow: '马上玩',
  back: '返回游戏房', practice: '练习模式', daily: '每日挑战',
  practiceNote: '不限次数 · 轻松享受打包乐趣', dailyNote: '每日小任务 · 20 Joy Coins',
  start: '开始游戏', replay: '再玩一次', tutorial: '玩法说明', close: '关闭',
  chooseMode: '你的小小礼物柜台', modeHint: '90 秒，把欢乐送到他们手中。', counterSign: '礼物柜台', setupLabel: '90 秒欢乐时光',
  score: '分数', best: '个人最高分', combo: '完美连击', time: '剩余时间',
  served: '送达礼物', perfect: '完美订单', maxCombo: '最高连击',
  coins: 'Joy Coins', pause: '暂停', resume: '继续游戏', restart: '重新开始', soundOn: '开启声音', soundOff: '关闭声音',
  paused: '休息一下吧', pausedNote: '顾客会等你。计时已暂停。',
  waiting: '下一位顾客正在路上！', waitingNote: '小物已准备好，新的心愿即将到来。',
  request: '他们的小小心愿', tray: '你的礼物托盘', shelf: '挑选可爱小物',
  wrapping: '最后，系上蝴蝶结', clear: '清空托盘', pack: '打包礼物',
  selectCustomer: '选择顾客', emptySlot: '空的礼物位置',
  remove: '移除', patience: '秒等待时间', wrapNeeded: '指定包装',
  waitingBadge: '等待中', servingBadge: '打包中', giftFor: '送给',
  perfectDelivery: '完美包裹！', delivery: '爱心送达！',
  wrongItems: '检查物品和数量。等待时间 −3 秒',
  wrongWrap: '试试他们指定的包装。等待时间 −3 秒',
  expired: '他们先走了。下一份礼物，重新加油！',
  roundFinished: '这一轮完成啦！', results: '小小礼物，快乐满满。',
  resultsNote: '每一个包裹，都是一份小小的欢乐。',
  goal: '今天的小任务', goalDone: '每日任务完成！',
  dailyGoals: { 'perfect-five': '一轮内送达 5 份完美包裹。', 'serve-ten': '一轮内送达 10 份包裹。', 'combo-four': '达成 4 次连续完美订单。' },
  rewardPending: '20 Joy Coins 待领取。钱包准备好后可以重试。',
  rewardCredited: '这一天的 20 Joy Coins 已领取！',
  rewardAlready: '今天的奖励已领取，继续挑战你的最高分吧！',
  rewardIncomplete: '再玩一轮每日挑战，完成今天的小任务吧。',
  practiceReward: '练习模式收获分数与微笑，每日挑战可获得 Joy Coins。',
  claim: '领取奖励', retry: '重试领取', walletWait: '钱包准备中。',
  walletChanged: '这份奖励属于获得它的钱包，请返回原来的账户重试。',
  pendingTitle: '一份奖励在等你', stickerUnlocked: '欢乐包裹贴纸已解锁！',
  stickerHint: '一轮内完成 5 份完美包裹，即可收藏欢乐包裹贴纸。',
  leaveTitle: '离开这一轮？', leaveNote: '这一轮的分数和奖励不会保存。',
  leave: '离开游戏', restartTitle: '重新开始这一轮？', restartNote: '当前游戏将结束。',
  confirmRestart: '重新开始', cancel: '继续打包',
  tutorialSteps: [
    '选择一位顾客，查看物品图案、数量和指定包装。',
    '点击货架小物放入托盘，点击托盘内的物品即可移除。',
    '选择正确包装，点击打包礼物。打包错误会扣除 3 秒等待时间。',
    '连续完美送达可获得连击加分。每轮 90 秒，随时可以暂停。',
  ],
  customers: { bunny: '兔兔', bear: '小熊', chick: '小鸡' },
  products: { 'bear-notebook': '小熊笔记本', 'bunny-pencil-case': '兔兔笔袋', 'bear-heart': '爱心钥匙扣', 'bubble-tea-keychain': '奶茶钥匙扣', 'paw-squishy': '肉球捏捏', 'kawaii-washi-tape': '可爱和纸胶带' },
  wraps: { 'pink-hearts': '粉色爱心', 'lavender-stars': '紫色星星', 'mint-dots': '薄荷圆点' },
};
export const getGiftRushCopy = language => language === 'zh' ? zh : en;
